### ISSUE TITLE
Webview is deprecated

### ISSUE THREAD

**Issue by j0nl1** [jim-at-jibba/react-native-game-pad#1]
Webview is no longer available from react-native and you need a package to load it.

https://github.com/react-native-community/react-native-webview

**Comment by jim-at-jibba** [comment]
Hey @j0nl1,

Thanks for pointing this out. I will make the update ASAP.

Cheers

**Comment by jim-at-jibba** [comment]
@j0nl1 I have updated the package to use the new webview package. Unfortunately, this is a breaking change pack now requires linking. 

Please refer to the readme for the new install instructions.

This is a real shame as it takes away from what the project originally was. I simple, JS only gamepad. 

Nevermind.
