### ISSUE TITLE
I am waiting for the update. 

### ISSUE THREAD

**Issue by poorvajappja** [jim-at-jibba/react-native-game-pad#11]
I am waiting for your update.

**Comment by poorvajappja** [comment]
Today 31-3-2021 the end of the march but no update.

**Comment by jim-at-jibba** [comment]
I have unfortunately not had the free time that I had expected. 

The rewrite will happen but I am not sure when. Please be patient.

Thanks

**Comment by ghost** [comment]
Thanks for your reply!!!
