### ISSUE TITLE
Not running with basic example - 'method' in source

### ISSUE THREAD

**Issue by bara495** [jim-at-jibba/react-native-game-pad#4]
TypeError: source is not an Object. (evaluating ''method' in source')

The error occurs with remote debugger off on Android emulator (Android 9.0).

On an almost empty project, with the following dependencies: 

```js
"dependencies": {
    "prop-types": "^15.6.1",
    "react": "16.8.3",
    "react-native": "0.59.4",
    "react-native-game-pad": "^1.0.0",
    "react-native-maps": "^0.24.0",
    "react-native-webview": "^5.8.1",
    "react-navigation": "^2.17.0",
    "react-redux": "^5.0.7",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-persist": "^5.9.1",
    "redux-saga": "^0.16.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.3",
    "@babel/runtime": "^7.4.3",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^24.7.1",
    "babel-preset-react-native": "^4.0.1",
    "eslint": "^5.16.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.17.1",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.12.4",
    "jest": "^24.7.1",
    "metro-react-native-babel-preset": "^0.53.1",
    "react-test-renderer": "16.8.3"
  },
```

![Screenshot_1557141877](https://user-images.githubusercontent.com/16253032/57222313-63e97300-7002-11e9-928b-dd84306deb5d.png)

**Comment by michaelhitzker** [comment]
got the same error, please fix

**Comment by michaelhitzker** [comment]
I found a workaround:
1) go to node_modules/react-native-game-pad/components/dual
2) copy the html in /web/index.html into a string (I created a new file for that for a better overview). Also, remove `<script src="./nipplejs.min.js"></script>`
My structure now looks at follows:

- dual
 - dual/web/
 - dual/dual-joystick.js
 - dual/nipplehtml.ts < html from index.html

3) copy the text in /web/nipplejs.min.js into a variable (I copied that into a new file, too)
structure:
- dual
 - dual/web/
 - dual/dual-joystick.js
 - dual/nipplehtml.ts < html from index.html
 - dual/nipplejsl.ts < contains a single string that contains the text from nipplejs.min.js

4) In dual/dual-joystick.js import the variables from the previously created files and replace `source={require("./web/index.html")}` with `source={{
              html: `${nipplejshtml}`
            }}`
5) In dual/dual-joystick.js at line 7 or something, replace 
``const js = (options, options2) => { let string = ` var joystick = nipplejs.create({``
with 
``const js = (options, options2) => { let string = `${nipplejs} var joystick = nipplejs.create({``
6) Voila

I only tested it with dual joysticks, but it should work with single as well.

I know this is not the best fix, but until the creator of react-native-game-pad gives us a proper fix, this should do the trick. 

The files I changed are in the ZIP file below


[rngamepadfix.zip](https://github.com/jim-at-jibba/react-native-game-pad/files/3340677/rngamepadfix.zip)

**Comment by fabio-als-freitas** [comment]
> I found a workaround:
> 
> 1. go to node_modules/react-native-game-pad/components/dual
> 2. copy the html in /web/index.html into a string (I created a new file for that for a better overview). Also, remove `<script src="./nipplejs.min.js"></script>`
>    My structure now looks at follows:
> 
> * dual
> * dual/web/
> * dual/dual-joystick.js
> * dual/nipplehtml.ts < html from index.html
> 
> 1. copy the text in /web/nipplejs.min.js into a variable (I copied that into a new file, too)
>    structure:
> 
> * dual
> * dual/web/
> * dual/dual-joystick.js
> * dual/nipplehtml.ts < html from index.html
> * dual/nipplejsl.ts < contains a single string that contains the text from nipplejs.min.js
> 
> 1. In dual/dual-joystick.js import the variables from the previously created files and replace `source={require("./web/index.html")}` with `source={{ html: `${nipplejshtml}` }}`
> 2. In dual/dual-joystick.js at line 7 or something, replace
>    `` const js = (options, options2) => { let string = ` var joystick = nipplejs.create({ ``
>    with
>    `` const js = (options, options2) => { let string = `${nipplejs} var joystick = nipplejs.create({ ``
> 3. Voila
> 
> I only tested it with dual joysticks, but it should work with single as well.
> 
> I know this is not the best fix, but until the creator of react-native-game-pad gives us a proper fix, this should do the trick.
> 
> The files I changed are in the ZIP file below
> 
> [rngamepadfix.zip](https://github.com/jim-at-jibba/react-native-game-pad/files/3340677/rngamepadfix.zip)

It works, Thank you!

**Comment by lzty634158** [comment]
very good！

**Comment by cabraljv** [comment]
now i recive a white screen ;-;

**Comment by jim-at-jibba** [comment]
Hey sorry for the delay, not using this at the moment and dont have time to look at fixing.

I do have an idea to rewrite without the webview dependency. Watch this space.

**Comment by bara495** [comment]
> I found a workaround:
> 
> 1. go to node_modules/react-native-game-pad/components/dual
> 2. copy the html in /web/index.html into a string (I created a new file for that for a better overview). Also, remove `<script src="./nipplejs.min.js"></script>`
>    My structure now looks at follows:
> 
> * dual
> * dual/web/
> * dual/dual-joystick.js
> * dual/nipplehtml.ts < html from index.html
> 
> 1. copy the text in /web/nipplejs.min.js into a variable (I copied that into a new file, too)
>    structure:
> 
> * dual
> * dual/web/
> * dual/dual-joystick.js
> * dual/nipplehtml.ts < html from index.html
> * dual/nipplejsl.ts < contains a single string that contains the text from nipplejs.min.js
> 
> 1. In dual/dual-joystick.js import the variables from the previously created files and replace `source={require("./web/index.html")}` with `source={{ html: `${nipplejshtml}` }}`
> 2. In dual/dual-joystick.js at line 7 or something, replace
>    `` const js = (options, options2) => { let string = ` var joystick = nipplejs.create({ ``
>    with
>    `` const js = (options, options2) => { let string = `${nipplejs} var joystick = nipplejs.create({ ``
> 3. Voila
> 
> I only tested it with dual joysticks, but it should work with single as well.
> 
> I know this is not the best fix, but until the creator of react-native-game-pad gives us a proper fix, this should do the trick.
> 
> The files I changed are in the ZIP file below
> 
> [rngamepadfix.zip](https://github.com/jim-at-jibba/react-native-game-pad/files/3340677/rngamepadfix.zip)

this approach works, thank you very much!!!
