### ISSUE TITLE
Not running with basic example 2 - cannot use 'in' operator to search for 'method' in 2 

### ISSUE THREAD

**Issue by bara495** [jim-at-jibba/react-native-game-pad#5]
TypeError: cannot use 'in' operator to search for 'method' in 2 

The error occurs with remote debugger ON on Android emulator (Android 9.0).
That is the only difference from #4... The problem seems to be somewhere in the source-method-in triangle.

On an almost empty project, with the following dependencies: 

```js
"dependencies": {
    "prop-types": "^15.6.1",
    "react": "16.8.3",
    "react-native": "0.59.4",
    "react-native-game-pad": "^1.0.0",
    "react-native-maps": "^0.24.0",
    "react-native-webview": "^5.8.1",
    "react-navigation": "^2.17.0",
    "react-redux": "^5.0.7",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-persist": "^5.9.1",
    "redux-saga": "^0.16.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.3",
    "@babel/runtime": "^7.4.3",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^24.7.1",
    "babel-preset-react-native": "^4.0.1",
    "eslint": "^5.16.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.17.1",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.12.4",
    "jest": "^24.7.1",
    "metro-react-native-babel-preset": "^0.53.1",
    "react-test-renderer": "16.8.3"
  },
```

![Screenshot_1557142860](https://user-images.githubusercontent.com/16253032/57222912-a1e79680-7004-11e9-9b7c-6e258fce9cac.png)

**Comment by fabio-als-freitas** [comment]
Same here

**Comment by jim-at-jibba** [comment]
Hey sorry for the delay, not using this at the moment and dont have time to look at fixing.

I do have an idea to rewrite without the webview dependency. Watch this space.

**Comment by jim-at-jibba** [comment]
I have some.more time and a need for this package again and am looking to rewritile it in the next few months. 

Sorry for the delay
