### ISSUE TITLE
cannot load nipplejs.min.js

### ISSUE THREAD

**Issue by afikmenashe21** [jim-at-jibba/react-native-game-pad#6]
Hey there ,

I'm trying to do what you mentioned , however I struggeling with this issue while loading the app:

Error: 'node_modules/react-native-game-pad/components/single/web/nipplejs.min.js' cannot be loaded as its extension is not registered in assetExts

Can you kindly help me figure out what should I do with it please?
Thanks :)

**Comment by jim-at-jibba** [comment]
Hey, 

Sorry for the late reply. Been busy and had no time. This version of the gamepad is broken. I am planning on rewriting this package removing the dependency on nipple.

**Comment by davidric** [comment]
Hi when this package available? I need it so much for my robot project. Thanks

**Comment by jim-at-jibba** [comment]
@davidric I started rewriting the package tonight. I will work on it as much as I can. Watch this space

**Comment by davidric** [comment]
Ok thank you for the update..
